seafood_landings:
  target: local
  outputs:

    local:
      type: postgres
      host: "{{ env_var('LOCAL_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('LOCAL_POSTGRES_PORT', '5435') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 4
      connect_timeout: 10
      retries: 1
      keepalives_idle: 0

    docker:
      type: postgres
      host: "{{ env_var('DOCKER_POSTGRES_HOST', 'postgres') }}"
      port: "{{ env_var('DOCKER_POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 4
      connect_timeout: 10
      retries: 1
      keepalives_idle: 0

