version: 2

models:
  - name: int_landings
    columns:
      - name: year
        data_tests:
          - not_null
      - name: state
        data_tests:
          - not_null
      - name: species
        data_tests:
          - not_null

  - name: int_recalls
    columns:
      - name: recall_number
        data_tests:
          - not_null
      - name: state
        data_tests:
          - not_null
